version: "3.3"
services:

  emailtidy-db:
    container_name: emailtidy-db
    env_file:
      - .env
    image: emailtidy-db
    build:
      context: ./backend/db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  emailtidy-py:
    container_name: emailtidy-py
    env_file:
      - .env
    image: emailtidy-py
    depends_on:
      - emailtidy-db
    build:
      context: ./backend/py
    ports:
      - 8000:8000
    volumes:
      # Bind these volumns for easy development without having to restart the containers. Remove for production.
      - type: bind
        source: ./backend/py/app
        target: /app
  
  emailtidy-react:
    container_name: emailtidy-react
    image: emailtidy-react
    depends_on:
      - emailtidy-py
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
    # Bind these volumns for easy development without having to restart the containers. Remove for production.
      - type: bind
        source: ./frontend
        target: /app

volumes:
  db-data: