"""add insert_ts columns

Revision ID: 4982f313895e
Revises: 5c2831f87aff
Create Date: 2023-05-08 05:06:11.505441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4982f313895e"
down_revision = "5c2831f87aff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scanned_emails",
        sa.Column("insert_ts", sa.DateTime(timezone=True), nullable=True, server_default=sa.sql.func.now()),
    )
    op.add_column(
        "unsubscribe_links",
        sa.Column("insert_ts", sa.DateTime(timezone=True), nullable=True, server_default=sa.sql.func.now()),
    )
    op.add_column(
        "linked_emails",
        sa.Column("insert_ts", sa.DateTime(timezone=True), nullable=True, server_default=sa.sql.func.now()),
    )
    op.add_column(
        "users",
        sa.Column("insert_ts", sa.DateTime(timezone=True), nullable=True, server_default=sa.sql.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("unsubscribe_links", "insert_ts")
    op.drop_column("scanned_emails", "insert_ts")
    op.drop_column("linked_emails", "insert_ts")
    op.drop_column("users", "insert_ts")
    # ### end Alembic commands ###
